const KEY='twilight-guild-v1',VAULT='vault';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID(),today=()=>new Date().toLocaleDateString('sv-SE');
const defaults={site:'暮光旅團',subtitle:'THE TWILIGHT GUILD',campaign:'灰霧邊境',home:'隊伍大廳',vault:'隊伍倉庫',party:'角色背包',hero:'暮光之下，冒險未央。',welcome:'歡迎回來，冒險者。在這裡收好戰利品，準備下一段旅程。',side:'冒險者檔案 / CAMPAIGN 01',motto:'故事尚未完結',mottoDetail:'每一次選擇，都留下痕跡。',vaultDescription:'共同的戰利品，留給下一段未知的旅程。',partyDescription:'每位冒險者保管的物品，全隊都能清楚查看。',treasures:'隊伍的寶藏',heroTag:'THE CHRONICLES OF OUR ADVENTURE',vaultTag:'SHARED TREASURY',partyTag:'THE ADVENTURERS',characterTag:'CHARACTER INVENTORY',inventoryTitle:'共用物資',footer:'冒險者公會'};
const textLabels={site:'網站名稱',subtitle:'英文副標題',campaign:'戰役名稱',home:'大廳名稱',vault:'倉庫名稱',party:'背包頁名稱',hero:'首頁標題',welcome:'首頁介紹',side:'側欄標題',motto:'側欄標語',mottoDetail:'側欄說明',vaultDescription:'倉庫介紹',partyDescription:'背包介紹',treasures:'寶藏區標題',heroTag:'首頁英文標題',vaultTag:'倉庫英文標題',partyTag:'背包英文標題',characterTag:'角色英文標題',inventoryTitle:'物資區標題',footer:'頁尾副標題'};
const categories=['裝備','消耗品','任務物品','補給','其他'],rarities=['未知','普通','非普通','稀有','非常稀有','傳奇'],statuses=['可使用','未鑑定','未解讀'];
const iconKeys=['🧪','🗡️','🛡️','🏹','💍','📜','🗺️','🥖','💎','🪄','🪙','🎒'];
function imageValid(s){return s===''||(typeof s==='string'&&s.startsWith(CLOUD_CONFIG.url+'/storage/v1/object/public/'+CLOUD_CONFIG.bucket+'/')&&/^[a-f0-9]{64}\.jpg$/.test(s.split('/').pop()))||(typeof s==='string'&&s.length<700000&&/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(s))}
function migrate(raw){const s=structuredClone(raw);if(!s||!Array.isArray(s.items))throw Error();if(s.version===2)return s;const names=[...new Set(['艾琳','索恩','米菈','芬恩',...s.items.map(i=>i.owner).filter(n=>n!=='隊伍倉庫')])],descriptions={'艾琳':'半精靈 · 遊俠','索恩':'矮人 · 戰士','米菈':'人類 · 法師','芬恩':'半身人 · 遊蕩者'};s.characters=names.map((name,n)=>({id:'character-'+n,name,info:descriptions[name]||'',note:''}));const map=new Map(s.characters.map(c=>[c.name,c.id])),avatars={};for(const [name,img] of Object.entries(s.avatars||{}))if(map.has(name))avatars[map.get(name)]=img;s.avatars=avatars;s.settings={...defaults};s.items=s.items.map(i=>({...i,owner:i.owner==='隊伍倉庫'?VAULT:map.get(i.owner),image:i.image||'',description:i.description||'',note:i.note||'',source:i.source||'',history:i.history||[]}));s.version=2;return s}
function valid(s){if(!s||s.version!==2||!Array.isArray(s.characters)||!Array.isArray(s.items)||!s.settings||!s.avatars||Array.isArray(s.avatars))return false;if(!Object.keys(defaults).every(k=>typeof s.settings[k]==='string'&&s.settings[k].trim()&&s.settings[k].length<=1000))return false;if(!s.characters.every(c=>c&&typeof c.id==='string'&&c.id!==VAULT&&typeof c.name==='string'&&c.name.trim()&&c.name.length<=80&&typeof c.info==='string'&&c.info.length<=200&&typeof c.note==='string'&&c.note.length<=5000))return false;const ids=s.characters.map(c=>c.id);if(new Set(ids).size!==ids.length||!Object.entries(s.avatars).every(([k,v])=>ids.includes(k)&&imageValid(v)))return false;const owners=new Set([VAULT,...ids]);return new Set(s.items.map(i=>i.id)).size===s.items.length&&s.items.every(i=>i&&typeof i.id==='string'&&typeof i.name==='string'&&i.name.trim()&&i.name.length<=100&&owners.has(i.owner)&&Number.isSafeInteger(i.qty)&&i.qty>=0&&i.qty<=999999&&['icon','category','rarity','status','source','note','description'].every(k=>typeof i[k]==='string'&&i[k].length<=5000)&&imageValid(i.image)&&Array.isArray(i.history)&&i.history.every(x=>typeof x==='string'))}
let state=migrate(seed);state.characters=[];state.items=[];state.avatars={};state.events=[];
let page='vault',dm=false,owner=VAULT,search='',category='全部類型',toastTimer;
function ownerName(id){return id===VAULT?state.settings.vault:state.characters.find(c=>c.id===id)?.name||'未知角色'}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function options(a,selected){return a.map(x=>`<option ${x===selected?'selected':''}>${esc(x)}</option>`).join('')}
function ownerOptions(selected,exclude){return [VAULT,...state.characters.map(c=>c.id)].filter(id=>id!==exclude).map(id=>`<option value="${esc(id)}" ${id===selected?'selected':''}>${esc(ownerName(id))}</option>`).join('')}
function editable(key,tag='span',className=''){return `<${tag} class="${className} ${dm?'editable':''}" ${dm?`data-text="${key}" role="button" tabindex="0" title="點選修改${esc(textLabels[key])}" aria-label="修改${esc(textLabels[key])}"`:''}>${esc(state.settings[key])}</${tag}>`}
function modal(html){$('#modalBody').innerHTML=html;if(!$('#modal').open)$('#modal').showModal()}
function close(){$('#modal').close()}
function art(icon,image=''){if(image)return `<span class="item-icon custom-art"><img src="${esc(image)}" alt=""></span>`;const n=iconKeys.indexOf(icon);return n<0?`<span class="item-icon">${esc(icon)}</span>`:`<span aria-hidden="true" class="item-icon item-art" style="--ix:${n%4};--iy:${Math.floor(n/4)}"></span>`}
function rarityClass(i){return ({'未知':'unknown','普通':'common','非普通':'uncommon','稀有':'rare','非常稀有':'epic','傳奇':'legendary'})[i.rarity]||'common'}
function itemCard(i){return `<button class="item-card ${rarityClass(i)}" data-item="${esc(i.id)}" aria-label="${esc(i.name)}，${i.qty} 件，${esc(i.status)}"><div class="slot-art">${art(i.icon,i.image)}<span class="amount">${i.qty}</span>${i.status==='未鑑定'?'<span class="unknown-mark">?</span>':''}</div><strong>${esc(i.name)}</strong><small><span class="rarity-dot"></span>${esc(i.rarity)} · ${esc(i.status)}</small></button>`}
function avatar(id,large=false){const a=state.avatars[id];return `<span class="avatar ${large?'large':''}">${a?`<img src="${esc(a)}" alt="${esc(ownerName(id))}的頭像">`:`<span>${esc(ownerName(id).slice(0,1))}</span>`}</span>`}
function partyStrip(){return `<div class="party-tabs">${state.characters.map(c=>`<button data-owner="${esc(c.id)}" class="${page==='party'&&owner===c.id?'active':''}">${avatar(c.id)}<span><b>${esc(c.name)}</b><small>${esc(c.info)||'尚未填寫角色資訊'}</small></span><span class="member-arrow">›</span></button>`).join('')}${dm?'<button class="add-character" data-character="new">＋ 新增角色</button>':''}</div>`}
function characterPanel(){const c=state.characters.find(c=>c.id===owner);if(!c)return '<div class="empty">先新增一位角色，即可建立背包。</div>';return `<section class="character-panel">${avatar(owner,true)}<div class="character-copy">${editable('characterTag','div','eyebrow')}<h2 ${dm?`class="editable" role="button" tabindex="0" data-character="${esc(owner)}" title="點選編輯角色"`:''}>${esc(c.name)}</h2><p ${dm?`class="editable" role="button" tabindex="0" data-character="${esc(owner)}"`:''}>${esc(c.info)||'尚未填寫角色資訊'}</p>${c.note?`<p class="character-note">${esc(c.note)}</p>`:''}<small>保管 ${state.items.filter(i=>i.owner===owner).reduce((n,i)=>n+i.qty,0)} 件物品 · 全隊可見</small></div>${dm?`<div class="character-actions"><button data-character="${esc(owner)}">編輯角色資料</button><button class="subtle" data-avatar="${esc(owner)}">＋ 上傳／更換頭像</button></div>`:''}</section>`}
function render(){if(!state.characters.some(c=>c.id===owner))owner=state.characters[0]?.id||VAULT;document.title=`${state.settings.site} · ${state.settings.footer}`;$('.brand').outerHTML=`<div class="brand"><span class="sigil">✧</span><span>${editable('site')}<small>${editable('subtitle')}</small></span></div>`;$('.side-label').innerHTML=editable('side');$('.side-bottom p').innerHTML=editable('motto');$('.side-bottom small').innerHTML=editable('mottoDetail');$('header>div').innerHTML=`${editable('campaign')} <span>/</span> <b id="breadcrumb">${esc(state.settings[page])}</b>`;$('nav').innerHTML=['home','vault','party'].map((p,n)=>`<div class="nav-row"><button data-page="${p}" class="${p===page?'active':''}">${['⌂','▦','♙'][n]} <span>${esc(state.settings[p])}</span></button>${dm?`<button class="rename-nav" data-text="${p}" aria-label="修改${textLabels[p]}" title="修改名稱">✎</button>`:''}</div>`).join('');$('footer>span').innerHTML=`${editable('site')} · ${editable('footer')}`;$('#mode').textContent=dm?'◈ DM 管理帳號':account?'帳號／登出':'DM 登入';const active=state.items.filter(i=>i.qty>0);let html='';
 if(page==='home')html=`<section class="hero">${editable('heroTag','div','eyebrow')}${editable('hero','h1')}${editable('welcome','p')}<div class="hero-meta"><span class="dot">● 戰役進行中</span>${editable('campaign')}<span>${state.characters.length} 位冒險者</span></div></section><div class="stats"><div class="stat"><small>隊伍成員</small><strong>${state.characters.length}</strong></div><div class="stat"><small>物品種類</small><strong>${active.length}</strong></div><div class="stat"><small>倉庫物品總件數</small><strong>${active.filter(i=>i.owner===VAULT).reduce((n,i)=>n+i.qty,0)}</strong></div><div class="stat"><small>待鑑定物品種類</small><strong>${active.filter(i=>i.status==='未鑑定').length}</strong></div></div>${partyStrip()}<section class="panel"><div class="section-head">${editable('treasures','h2')}${dm?'<button class="primary" data-add>＋ 發放道具</button>':''}</div><div class="inventory">${active.slice(0,12).map(itemCard).join('')||'<div class="empty">還沒有物品。</div>'}</div></section>`;
 if(page==='vault'||page==='party')html=`<div class="page-intro">${editable(page+'Tag','div','eyebrow')}${editable(page,'h1')}${editable(page+'Description','p')}</div><div class="section-head"><span class="tag">${page==='vault'?'全隊共用 · 物品流向可追溯':'全隊可見 · 點選角色查看'}</span>${dm?'<button class="primary" data-add>＋ 發放道具</button>':''}</div>${partyStrip()}${page==='party'?characterPanel():''}<div class="toolbar"><input id="search" aria-label="搜尋道具" placeholder="搜尋道具、來源或備註…" value="${esc(search)}"><select id="category" aria-label="道具分類">${options(['全部類型',...categories],category)}</select><label class="zero-filter"><input type="checkbox" id="showZero">包含已耗盡</label></div><section class="inventory-frame"><div class="inventory-caption"><span>▦ &nbsp; ${page==='vault'?editable('inventoryTitle'):esc(ownerName(owner))+'的行囊'}</span><small>點選道具查看或編輯</small></div><div class="inventory" id="results"></div><div class="inventory-legend"><span>● 普通</span><span style="color:#78cba2">● 非普通</span><span style="color:#79aefe">● 稀有</span><span style="color:#c49cff">● 非常稀有</span><span style="color:#efba60">● 傳奇</span><span>? 未鑑定</span></div></section>`;
 $('#content').innerHTML=html;filter();$('#search')?.addEventListener('input',e=>{search=e.target.value;filter()});$('#category')?.addEventListener('change',e=>{category=e.target.value;filter()});$('#showZero')?.addEventListener('change',filter)}
function filter(){if(!$('#results'))return;const q=search.toLowerCase(),matches=state.items.filter(i=>i.owner===(page==='vault'?VAULT:owner)&&(i.qty>0||$('#showZero').checked)&&(category==='全部類型'||i.category===category)&&`${i.name} ${i.source} ${i.note} ${i.description}`.toLowerCase().includes(q));$('#results').innerHTML=matches.map(itemCard).join('')||'<div class="empty">這裡還沒有符合的物品。</div>';if(!search&&category==='全部類型')$('#results').insertAdjacentHTML('beforeend',Array.from({length:Math.max(0,18-matches.length)},()=>'<div class="empty-slot" aria-hidden="true"><span>✧</span></div>').join(''))}
function editText(key){if(!dm||!(key in defaults))return;modal(`<div class="eyebrow">CUSTOMIZE YOUR GUILD</div><h2>${esc(textLabels[key])}</h2><form id="textForm"><label>顯示文字<textarea name="text" maxlength="1000" required>${esc(state.settings[key])}</textarea></label><p class="upload-help">儲存後會同步更新網站中的相同名稱。</p><div class="actions"><button type="button" data-close>取消</button><button class="primary">儲存名稱</button></div></form>`);$('#textForm').onsubmit=async e=>{e.preventDefault();const value=new FormData(e.target).get('text').trim();if(!value){toast('名稱不能留白。');return}const next=structuredClone(state);next.settings[key]=value;if(await persist(next)){close();render();toast('名稱已更新')}}}
function editCharacter(id){if(!dm)return;const c=state.characters.find(c=>c.id===id);modal(`<div class="eyebrow">ADVENTURER PROFILE</div><h2>${c?'編輯角色資料':'新增角色'}</h2><form id="characterForm"><div class="form-grid"><label class="wide">角色名稱<input name="name" maxlength="80" value="${esc(c?.name||'')}" required></label><label class="wide">角色資訊<input name="info" maxlength="200" placeholder="例如：精靈 · 法師 · 等級 5" value="${esc(c?.info||'')}"></label><label class="wide">角色介紹／備註<textarea name="note" maxlength="5000">${esc(c?.note||'')}</textarea></label></div><p class="upload-help">角色改名後，原有頭像與物品會保留。新增後可上傳頭像。</p><div class="actions"><button type="button" data-close>取消</button><button class="primary">儲存角色</button></div></form>`);$('#characterForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));Object.keys(d).forEach(k=>d[k]=d[k].trim());if(!d.name){toast('請填寫角色名稱。');return}if(state.characters.some(x=>x.id!==id&&x.name===d.name)){toast('已有同名角色，請使用不同名稱。');return}const next=structuredClone(state),target=c?next.characters.find(x=>x.id===id):{id:uid()};Object.assign(target,d);if(!c)next.characters.push(target);if(await persist(next)){owner=target.id;page='party';close();render();toast('角色資料已保存')}}}
async function decodeItemImage(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024)throw Error('請選擇 8 MB 以內的 JPG、PNG 或 WebP。');const img=await createImageBitmap(file);try{if(img.width<16||img.height<16||img.width*img.height>40000000)throw Error('圖片尺寸需至少 16 像素，且不超過 4,000 萬像素。');const canvas=document.createElement('canvas');canvas.width=canvas.height=384;const ctx=canvas.getContext('2d');ctx.fillStyle='#091321';ctx.fillRect(0,0,384,384);const ratio=Math.min(384/img.width,384/img.height),w=img.width*ratio,h=img.height*ratio;ctx.drawImage(img,(384-w)/2,(384-h)/2,w,h);return canvas.toDataURL('image/jpeg',.86)}finally{img.close()}}
function itemForm(id){if(!dm)return;const old=state.items.find(i=>i.id===id),i=old||{name:'',icon:'🧪',qty:1,owner:page==='party'?owner:VAULT,category:'裝備',rarity:'未知',status:'可使用',source:'',description:'',note:'',image:''};let image=i.image,loadVersion=0;
 modal(`<div class="eyebrow">ITEM EDITOR</div><h2>${old?'編輯道具':'發放一件新道具'}</h2><form id="itemForm"><div class="item-image-editor"><div id="itemPreview">${art(i.icon,image)}</div><div><label class="upload-button">上傳道具圖片<input id="itemImage" type="file" accept="image/jpeg,image/png,image/webp"></label><button type="button" id="clearImage">改用內建圖示</button><small id="imageStatus" role="status">JPG／PNG／WebP，最大 8 MB</small></div></div><div class="form-grid"><label class="wide">道具名稱<input name="name" maxlength="100" value="${esc(i.name)}" required></label><label>內建圖示<select name="icon">${options(iconKeys,i.icon)}</select></label><label>數量<input name="qty" type="number" min="${old?0:1}" max="999999" value="${i.qty}" required></label><label>存放位置<select name="owner">${ownerOptions(i.owner)}</select></label><label>類型<select name="category">${options(categories,i.category)}</select></label><label>稀有度<select name="rarity">${options(rarities,i.rarity)}</select></label><label>狀態<select name="status">${options(statuses,i.status)}</select></label><label class="wide">取得來源<input name="source" maxlength="200" value="${esc(i.source)}"></label><label class="wide">道具描述／效果<textarea name="description" maxlength="5000">${esc(i.description)}</textarea></label><label class="wide">公開備註<textarea name="note" maxlength="5000">${esc(i.note)}</textarea></label></div><div class="actions"><button type="button" data-close>取消</button><button class="primary" id="saveItem">${old?'儲存變更':'新增道具'}</button></div></form>`);
 const form=$('#itemForm'),preview=$('#itemPreview'),save=$('#saveItem'),status=$('#imageStatus'),refreshImage=()=>preview.innerHTML=art(form.elements.icon.value,image);form.elements.icon.onchange=refreshImage;
 $('#clearImage').onclick=()=>{loadVersion++;image='';$('#itemImage').value='';save.disabled=false;status.textContent='使用內建圖示';refreshImage()};
 $('#itemImage').onchange=async e=>{const file=e.target.files[0];if(!file)return;const current=++loadVersion;save.disabled=true;status.textContent='正在處理圖片…';try{const result=await decodeItemImage(file);if(current!==loadVersion||!form.isConnected)return;image=result;refreshImage();status.textContent='圖片已準備好，儲存道具後套用'}catch(err){if(current===loadVersion&&form.isConnected){status.textContent=err.message;toast(err.message)}}finally{if(current===loadVersion&&form.isConnected)save.disabled=false}};
 form.onsubmit=async e=>{e.preventDefault();if(save.disabled)return;const d=Object.fromEntries(new FormData(form));for(const k of Object.keys(d))d[k]=d[k].trim();d.qty=Number(d.qty);if(!d.name||!Number.isSafeInteger(d.qty)||d.qty<(old?0:1)||d.qty>999999){toast('請確認道具名稱與數量。');return}const next=structuredClone(state);d.image=image;if(old){const item=next.items.find(x=>x.id===id),log=`${today()} · 編輯道具「${item.name}」→「${d.name}」，數量 ${item.qty} → ${d.qty}，保管：${ownerName(item.owner)} → ${ownerName(d.owner)}`;Object.assign(item,d);item.history.push(log)}else next.items.unshift({...d,id:uid(),history:[`${today()} · 獲得 ${d.qty} 件，存放於${ownerName(d.owner)}`]});if(await persist(next)){close();render();toast('道具已保存')}}}
function detail(id){const i=state.items.find(x=>x.id===id);if(!i)return;modal(`<div class="detail">${art(i.icon,i.image)}<span class="eyebrow">${esc(i.category)} / ${esc(i.rarity)}</span><h2>${esc(i.name)} <span style="color:var(--gold)">× ${i.qty}</span></h2><div><span class="tag">${esc(i.status)}</span><span class="tag">${esc(ownerName(i.owner))}</span></div><p><b>取得來源</b><br>${esc(i.source)||'未記錄'}</p><p><b>描述／效果</b><br>${esc(i.description)||'尚無描述'}</p><p><b>公開備註</b><br>${esc(i.note)||'尚無備註'}</p><div class="history">${i.history.map(h=>`<div>${esc(h)}</div>`).join('')||'尚無異動紀錄'}</div></div>${dm?`<div class="actions"><button class="primary" data-edit-item="${esc(id)}">編輯道具內容與圖片</button></div>`:''}${dm&&i.qty>0?`<form id="move"><div class="form-grid" style="margin-top:20px"><label>操作<select name="action"><option>轉交物品</option><option>消耗物品</option></select></label><label>數量<input name="qty" type="number" min="1" max="${i.qty}" value="1" required></label><label class="wide" id="targetLabel">轉交至<select name="target">${ownerOptions(undefined,i.owner)}</select></label></div><div class="actions"><button>確認操作</button></div></form>`:''}<div class="actions"><button data-close>關閉</button></div>`);if(!$('#move'))return;$('#move [name=action]').onchange=e=>$('#targetLabel').hidden=e.target.value==='消耗物品';$('#move').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),n=Number(d.qty),next=structuredClone(state),from=next.items.find(x=>x.id===id);if(!from||!Number.isSafeInteger(n)||n<1||n>from.qty){toast('數量已變動，請重新開啟道具。');return}if(d.action==='轉交物品'&&![VAULT,...state.characters.map(c=>c.id)].includes(d.target)){toast('請先新增可接收物品的角色。');return}from.qty-=n;const log=`${today()} · ${d.action==='消耗物品'?`消耗 ${n} 件`:`從${ownerName(i.owner)}轉交 ${n} 件至${ownerName(d.target)}`}`;from.history.push(log);if(d.action==='轉交物品')next.items.unshift({...structuredClone(i),id:uid(),qty:n,owner:d.target,history:[...i.history,log]});if(await persist(next)){close();render();toast('物品紀錄已更新')}}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-page],[data-add],[data-item],[data-owner],[data-close],[data-text],[data-character],[data-edit-item]');if(!b)return;if(b.hasAttribute('data-close'))close();if(b.dataset.text)editText(b.dataset.text);if(b.dataset.character)editCharacter(b.dataset.character);if(b.dataset.page){page=b.dataset.page;search='';category='全部類型';render()}if(b.hasAttribute('data-add'))itemForm();if(b.dataset.item)detail(b.dataset.item);if(b.dataset.editItem)itemForm(b.dataset.editItem);if(b.dataset.owner){owner=b.dataset.owner;page='party';search='';category='全部類型';render()}});
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[role=button]:not(button)')){e.preventDefault();e.target.click()}});
$('#mode').onclick=loginDialog;
$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`${state.settings.site.replace(/[<>:"/\\|?*]/g,'-')}-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('#import').onclick=()=>{if(!dm){toast('請先登入 DM 帳號');return}$('#file').click()};$('#file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>15000000)throw Error();const s=migrate(JSON.parse(await f.text()));if(!valid(s))throw Error();if(confirm('匯入會取代目前紀錄（包含角色、圖片與名稱）。建議先匯出備份，確定匯入嗎？')&&await persist(s)){render();toast('紀錄已匯入')}}catch{toast('檔案格式不符或超過 15 MB，未變更原有紀錄。')}e.target.value=''};
render();startCloud();
