// Avatar images are decoded locally and cropped into compact JPEGs before saving.
document.addEventListener('click',e=>{const b=e.target.closest('[data-avatar]');if(b&&dm)editAvatar(b.dataset.avatar)});
function editAvatar(person){
 modal(`<div class="eyebrow">ADVENTURER PORTRAIT</div><h2>${esc(ownerName(person))}的頭像</h2><p class="upload-help">選擇圖片後，調整縮放與位置。保存前不會更動目前頭像。</p><div class="crop-stage"><canvas id="crop" width="320" height="320" aria-label="頭像裁切預覽"></canvas><span id="cropHint">選擇一張冒險者肖像</span></div><label class="upload-button">選擇圖片<input id="portraitFile" type="file" accept="image/jpeg,image/png,image/webp"></label><p class="upload-help">JPG、PNG 或 WebP，最大 8 MB。僅保存裁切後的頭像。</p><div class="crop-controls"><label>縮放<input id="zoom" type="range" min="1" max="3" step="0.01" value="1" disabled></label><label>水平位置<input id="panX" type="range" min="0" max="1" step="0.01" value="0.5" disabled></label><label>垂直位置<input id="panY" type="range" min="0" max="1" step="0.01" value="0.5" disabled></label></div><div class="actions">${state.avatars?.[person]?'<button id="removePortrait">移除頭像</button>':''}<button data-close>取消</button><button id="savePortrait" class="primary" disabled>儲存頭像</button></div>`);
 let bitmap=null,version=0;const canvas=$('#crop'),ctx=canvas.getContext('2d');
 const draw=()=>{if(!bitmap)return;const scale=Math.max(320/bitmap.width,320/bitmap.height)*Number($('#zoom').value),w=bitmap.width*scale,h=bitmap.height*scale;ctx.fillStyle='#101823';ctx.fillRect(0,0,320,320);ctx.drawImage(bitmap,-(w-320)*Number($('#panX').value),-(h-320)*Number($('#panY').value),w,h)};
 ['zoom','panX','panY'].forEach(id=>$('#'+id).oninput=draw);
 $('#portraitFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;const current=++version;$('#savePortrait').disabled=true;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024){toast('請選擇 8 MB 以內的 JPG、PNG 或 WebP 圖片。');return}try{const next=await createImageBitmap(file);if(current!==version||!canvas.isConnected){next.close();return}if(next.width<16||next.height<16||next.width*next.height>40000000){next.close();throw Error()}bitmap?.close();bitmap=next;$('#zoom').value='1';$('#panX').value=$('#panY').value='0.5';document.querySelectorAll('.crop-controls input').forEach(i=>i.disabled=false);$('#cropHint').hidden=true;draw();$('#savePortrait').disabled=false}catch{toast('無法讀取圖片，請換一張圖片（最大 4,000 萬像素）。')}};
 $('#savePortrait').onclick=async()=>{if(!bitmap||!dm)return;const next=structuredClone(state);next.avatars={...next.avatars,[person]:canvas.toDataURL('image/jpeg',0.86)};if(await persist(next)){close();render();toast(`${ownerName(person)}的頭像已保存`)}};
 if($('#removePortrait'))$('#removePortrait').onclick=async()=>{const next=structuredClone(state);delete next.avatars[person];if(await persist(next)){close();render();toast('已恢復預設頭像')}};
 $('#modal').addEventListener('close',()=>{version++;bitmap?.close()},{once:true});
}
